### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by juliensechaud** [jawj/NSMutableAttributedString-InlineStyles#1]
Hi,

it works great with AvenirNext font but if I try to put HelveticaNeue it crashes.
Any idea ?

thanks for this tool !
Julien

**Comment by jawj** [comment]
I suspect this is a problem with the convenience method that takes only a font name and assumes suffices like -Italic and -BoldItalic, whereas perhaps Helvetica Neue calls its italic -Oblique. 

Your proximate error is probably caused by adding a UIFont that evaluates to nil to an array. Is that consistent with what you see logged?

Try using the method that takes four full font names, and make sure you're using the correct ones! I guess I ought to update the library to find the different font variants in the proper way, though this may be less flexible.
